# Generated by Django 4.1.13 on 2024-03-15 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("39aed41e-2d09-4ecb-94d2-7b7b071e6ed4"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
